### ISSUE TITLE
shared params

### ISSUE THREAD

**Issue by gunney1** [sstsimulator/sst-core#756] opened 2021-11-12 17:00 UTC
New feature request:
----------------------
I would like to request a way to efficiently add parameters for sharing with all BaseComponents (or all C++ code).  Currently, the way to do this is to duplicate this data for every and every component.  This is not scalable for simulations with very large numbers of components.  In our code, the first component on each MPI task caches the data in a singleton.  Other components on the same task access the data through the singleton, so that's scalable.  Currently, the shared data has to be duplicated for all components, because we don't know which component will be allocated first on any given MPI task.  A lot of time is spent generating data that is never used.

Is it possible to add a Python method (maybe call it addSharedParams) analogous to addParams but not bound to a Component?  Don't copy this data for each component, but put it where all C++ code can access it, maybe in SST::Simulation::getSharedParams().

Thank you.

**Comment by feldergast** [comment] 2021-11-12 20:47
A very similar feature exists (it was committed just a bit before the 11.1 release.  They are called global parameters.  I‘ll post a short tutorial on how to use them later this weekend when I can sit down at my computer.  They are supported in both the python and new JSON input formats.

**Comment by gunney1** [comment] 2021-11-12 20:53
Thanks.  That would be great if it's a single copy accessible by all components on the MPI process, not a deep copy on each and every component.

**Comment by feldergast** [comment] 2021-11-13 14:39
We have use cases where subsets of components share parameter values, so have to have a way to differentiate since one key can have different values across the subsets.  The solution was to have a global group of named parameter sets.  Each rank gets only one copy of each named set.  You add parameters to a set using:

sst.addGlobalParams(set_name, dict_of_key_value_pairs)

Then, you can add these sets to each Component/SubComponent using:

comp.addGlobalParamSet(set_name)

You can add multiple global parameter sets to components.  These parameters are then available directly through the Params object passed into each Component/SubComponent when it is created.  When calling find() on the Params object, it will first look for "local" params (added using comp.addParam() or comp.addParams() call), and then it will look through the global sets in the order they were inserted using comp.addGlobalParamSet().  It will return the first value it finds for that key.  In this way, the Component/SubComponent doesn't need to know that it's looking for a global/shared parameter, all of that is set up in the python input file.

The memory overhead here is a single pointer for each global parameter set a Params object is "subscribed" to.

I hope that functionality will meet your needs.

**Comment by gunney1** [comment] 2021-11-15 18:32
I think that should work for us.  Thank you.

**Comment by gunney1** [comment] 2021-12-17 16:17
I'm having trouble with this feature running MPI multitask.  Either a bug or I'm not using it correctly.
Running sstcore-11.1.0.
How to reproduce:

Create component to print out Params:
```
#pragma once

#include <sst/core/component.h>
#include <string>
#include <unistd.h>

namespace DistWork {

static std::string to_string(const SST::Params &p) {
  std::ostringstream os;
  p.print_all_params(os);
  return os.str();
}

class ParamsPrinter : public SST::Component {
public:
  SST_ELI_REGISTER_COMPONENT(
    ParamsPrinter, "DistWork", "ParamsPrinter",
    SST_ELI_ELEMENT_VERSION(1,0,0),
    "Parameters printer",
    COMPONENT_CATEGORY_UNCATEGORIZED )

  ParamsPrinter(SST::ComponentId_t id, SST::Params& params)
  : SST::Component(id)
    {
      sleep(getRank().rank);
      std::cout << "rank=" << getRank().rank << ' ' << to_string(params) << std::endl;
    }
};

}
```

Here is a python script to create some components that use global parameters.  One global parameter set is inserted before the component creation, the other after.
```
import sst

before = dict(x='before', xIds=[])
after = dict(y='after', yIds=[])

sst.addGlobalParams('SharedBefore', before)

for i in range(2):
  before['xIds'].append(i)
  after['yIds'].append(i)
  comp = sst.Component(f'c{i}', 'DistWork.ParamsPrinter')
  comp.addParam('id', i)
  comp.addGlobalParamSet('SharedBefore')
  comp.addGlobalParamSet('SharedAfter')

sst.addGlobalParams('SharedAfter', after)
```

Running with 1 task:
```
> mpirun -np 1 sst srcdir/tests/detest.py
WARNING: Building component "c0" with no links assigned.
rank=0 Local params:
  key=id, value=0
Global params:
  key=<set_name>, value=SharedBefore
  key=x, value=before
  key=xIds, value=[]
  key=y, value=after
  key=yIds, value=[0, 1]

WARNING: Building component "c1" with no links assigned.
rank=0 Local params:
  key=id, value=1
Global params:
  key=<set_name>, value=SharedBefore
  key=x, value=before
  key=xIds, value=[]
  key=y, value=after
  key=yIds, value=[0, 1]
```
Both shared param sets show up for both components, but the presence of `value=SharedBefore` and absence of `value=SharedAfter` looks inconsistent to me.  `xIds` is empty but that makes sense because i set `SharedBefore` before appending to `xIds`.

Running with 2 tasks:
```
> mpirun -np 2 sst srcdir/tests/detest.py
WARNING: Building component "c0" with no links assigned.
WARNING: Building component "c1" with no links assigned.
rank=0 Local params:
  key=id, value=0
Global params:
  key=<set_name>, value=SharedBefore
  key=x, value=before
  key=xIds, value=[]
  key=<set_name>, value=
  key=y, value=after
  key=yIds, value=[0, 1]

rank=1 Local params:
  key=id, value=1
Global params:
  key=<set_name>, value=SharedBefore
  key=x, value=before
  key=xIds, value=[]
```
On rank 1, the param set shared after defining components is gone.  Bug or feature?

Is it possible to define global param sets any time during the python script, so that data like `yIds` can be built during the python script?

**Comment by feldergast** [comment] 2021-12-18 00:40
Both the serial and parallel runs should be the same.  Also, I don't believe it matters where you set the global params in the script, they key off of names that don't resolve until after the script is run.  The tests in core don't use the print function from the Params, but rather call Params::find and print the result.  It could be an issue in the print statement, or it could be something down deeper.  I'll take a look.

You are also correct that the addGlobalParams() call will take a snapshot of any list/map/set (really of anything) that is passed into it.  The call calls the str() function of the inputs and pushes them directly into the C++ API.

**Comment by feldergast** [comment] 2021-12-18 01:04
I changed the core test to use two global param sets, with one created before the components and one after.  All the parameters get to the correct spot, even for multi-rank jobs.  I'll take a look at the print_all_params function when I get a chance and make sure it's doing the right thing.

**Comment by gunney1** [comment] 2021-12-18 01:33
In my reproducer, when `print_all_params` doesn't show `SharedAfter`, `params.contains("y")` returns `false`.  This indicates that it `params` really doesn't have the second global param set.  With some mods to the output, I get
With 1 rank:
```
> mpirun -np 1 sst srcdir/tests/globalparamstest.py 
WARNING: Building component "c0" with no links assigned.
rank=0 params.contains("x")=1 params.contains("y")=1 params is Local params:
  key=id, value=0
Global params:
  key=<set_name>, value=SharedBefore
  key=x, value=before
  key=xIds, value=[]
  key=y, value=after
  key=yIds, value=[0, 1]

WARNING: Building component "c1" with no links assigned.
rank=0 params.contains("x")=1 params.contains("y")=1 params is Local params:
  key=id, value=1
Global params:
  key=<set_name>, value=SharedBefore
  key=x, value=before
  key=xIds, value=[]
  key=y, value=after
  key=yIds, value=[0, 1]
```

With 2 ranks:
```
> mpirun -np 2 sst srcdir/tests/globalparamstest.py
WARNING: Building component "c0" with no links assigned.
WARNING: Building component "c1" with no links assigned.
rank=0 params.contains("x")=1 params.contains("y")=1 params is Local params:
  key=id, value=0
Global params:
  key=<set_name>, value=SharedBefore
  key=x, value=before
  key=xIds, value=[]
  key=<set_name>, value=
  key=y, value=after
  key=yIds, value=[0, 1]

rank=1 params.contains("x")=1 params.contains("y")=0 params is Local params:
  key=id, value=1
Global params:
  key=<set_name>, value=SharedBefore
  key=x, value=before
  key=xIds, value=[]
```

**Comment by feldergast** [comment] 2021-12-18 05:14
Might be  a serialization issue then.  I'll have to figure out what's different in your reproducer and the core test.

**Comment by feldergast** [comment] 2022-01-04 21:34
I think I figured this out.  It exhibits when a set of shared params is referenced before having anything set in it.  In that case, a new params object is added to the global map that tracks them, but is not properly initialized with the name of the set.  This means it will work fine in serial, though the name will not show up when using print_all_params(), but it will not work properly for parallel jobs, other than on rank 1.  I should have a fix later today.

**Closed** 2022-04-14 16:47 UTC
