### ISSUE TITLE
Trac: #383 SST generates boost serialization warnings

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#5] opened 2015-10-07 14:30 UTC
This ticket is to document an issue with SSTs interaction with boost (version1.56 at the time of this issue). 

SST serialization code sstcoreserializationcore.h , sstcoreserializationelement.h and others generate a significant amount of warnings related to boost serialization. Many of these warnings are in boost file mplprint.hpp and are related to signedunsigned comparison or divide by zero warnings. 

According to boost issue #4953, these warnings (such as code causing a divide by zero) are intentional to assist users in tracing the templates used in the code. 

These warnings are a significant distraction from real warnings and have had no impact on operation of SST. Therefore they are being ignored via some gcc and clang pragmas 

search for 
#pragma GCC diagnostic push 
#pragma GCC diagnostic ignored -Wsign-compare 
#pragma clang diagnostic push 
#pragma clang diagnostic ignored -Wdivision-by-zero 

These pragmas are being created for gcc 4.6 and later and current versions of clang. gcc versions earlier than 4.6 will still generate the warnings. 

While the warnings are being ignored, they still exist for a reason. In the future, it is advised that the issues causing serialization warnings be investigated and addressed as necessary.

**Comment by bjmoor** [comment] 2016-01-19 19:26
Is this a bug to fix in SST?  As the issue is documented now, can we close this issue?

**Comment by bjmoor** [comment] 2016-07-07 14:49
There is no more Boost Serialization code.

**Closed by bjmoor** 2016-07-07 14:49 UTC
Labels: Bug, SST-Core, Trunk
