### ISSUE TITLE
Fix ill-formed JSON output

### ISSUE THREAD

**Issue by nicmcd** [sstsimulator/sst-core#634] opened 2021-05-12 17:46 UTC
In reference to this line of code: https://github.com/sstsimulator/sst-core/blob/4216b05a431c862c2d9382a28d2998b6cabb3cd8/src/sst/core/statapi/statoutputjson.cc#L93

It produces ill-formed JSON standard output:
```
{
   "rank" : 1

   "components" : [
      {
   <truncated here>
```
As shown, there is no comma after `"rank" : 1` however the JSON standard demands this. Since this code always prints the components, it should be safe to simply always add the comma.

**Comment by nicmcd** [comment] 2021-05-12 17:59
I've used both [nlohmann::json](https://github.com/nlohmann/json) quite extensively. I highly suggest using this instead of writing your own JSON output as they've spent a lot of time time making it easy to use (works like an STL container) and is JSON compliant (RFC 8259) which means that it will work with any standardized JSON library.

**Comment by nmhamster** [comment] 2021-05-12 19:38
@nicmcd - should have the "," added in #635. Let us know if that fixes this specific issue for you.

**Comment by nicmcd** [comment] 2021-05-12 21:50
Without testing it, I'm confident that this will fix this specific issue. Can you add a unit test for this? I suggest using a script that reads the output JSON using python, which is fairly pedantic in its formatting requirements:

python3 -c "import json; fd = open('<filename>'); json.load(fd)"

**Comment by nmhamster** [comment] 2021-05-18 03:16
@allevin - how would we add a test like this into the new test framework (see comment above)?

**Comment by allevin** [comment] 2021-05-18 14:15
> @allevin - how would we add a test like this into the new test framework (see comment above)?

@nmhamster A test for JSON would be added to the core tests.  We need a core test element that will can be loaded via an an SDL input file that when runs generates the JSON you want to check.  We would then just run @nicmcd recommendation to load the JSON formatted statistic file to verify its well formatted, and I would also recommend that we test it against a golden copy of the statistic file to see if it ever changes...  I just need someone to give me the core test element and SDL file.  I can do the rest.

**Comment by feldergast** [comment] 2021-05-18 14:25
There's already a StatisticsComponent element in the testElements directory and a test file in the tests directory.  We have not yet enable the test in a test suite, but we could modify the associated python file to take the type of output as an argument.  We could then create all the different output types with the same python file.  Looks like the StatisticsComponent code needs a little work, but should be easy to get ready.  At some point, we probably want to extend the test to use stats in SubComponents as well.

We could actually use the json parser as part of the test, but it would be just as reasonable to check the reference file using the json parser and then just compare to the reference file.

**Comment by allevin** [comment] 2021-05-18 14:44
> We could actually use the json parser as part of the test, but it would be just as reasonable to check the reference file using the json parser and then just compare to the reference file.   I

I agree that reference file will be enough, but loading using the JSON should be a fairly quick test, and it will confirm that the file is well-formed.

**Comment by calewis** [comment] 2021-07-27 03:03
@feldergast and @nmhamster should we just use this recommendation.  

> I've used both nlohmann::json quite extensively. 

@nicmcd I assume "both" is just a typo? Or did you have another recommendation? 

Anyways AFAICT nlohmann::json is a single header and MIT licensed, so I think we could just drop the header somewhere?  We might want to check for compile time regressions, but I agree with @nicmcd on finding a library solution especially if we plan to expand our use of json going forward.

**Comment by nicmcd** [comment] 2021-07-27 17:05
I can't remember what was going through my head with "both". I'm used nlohmann/json and jsoncpp. nlohmann/json is way better and standards compliant.

**Comment by calewis** [comment] 2021-07-29 20:59
@nmhamster is this fixed? Can we close it?

**Comment by nmhamster** [comment] 2021-07-29 21:01
@calewis - yes in PR #635

**Closed** 2021-07-29 21:02 UTC
Labels: Bug, SST-Core, SST-Statistics
